# Uncomment this line to define a global platform for your project

platform :ios, ‘8.0’
use_frameworks!
target ‘Training’ do
pod 'Fabric'
pod 'Crashlytics'
pod 'TPKeyboardAvoiding'
pod 'DZNEmptyDataSet'
pod 'JVFloatLabeledTextField’, :git => ‘https://github.com/valabal/JVFloatLabeledTextField.git’
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'  
pod 'Masonry'
pod 'JSONModel'
pod 'MBProgressHUD'
pod 'Colours'
pod 'DateTools'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Crash'
pod 'GoogleSignIn'
pod 'PXAlertView’, :git => ’https://github.com/valabal/PXAlertView.git’
pod 'TTTAttributedLabel'
pod 'Fabric'
pod 'Crashlytics'
pod 'Alamofire', '~> 4.0'
pod 'EVReflection'
pod 'INTULocationManager'
end


